package com.siruiman.crosslogistics.mapper;

import com.siruiman.crosslogistics.model.Bizdictionary;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface BizdictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    int insert(Bizdictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    Bizdictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */
    List<Bizdictionary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bizdictionary
     *
     * @mbggenerated
     */

    List<Bizdictionary> selectBizdictionaryByParentId(@Param("parentId") Integer parentId);

    int updateByPrimaryKey(Bizdictionary record);

    //void deleteBizdictionaryByParentId(@Param("parentId") Integer parentId);


}