package com.siruiman.crosslogistics.mapper;

import com.siruiman.crosslogistics.model.WxpayGoods;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface WxpayGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer wxpayGdNumberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_goods
     *
     * @mbggenerated
     */
    int insert(WxpayGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_goods
     *
     * @mbggenerated
     */
    WxpayGoods selectByPrimaryKey(Integer wxpayGdNumberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_goods
     *
     * @mbggenerated
     */
    List<WxpayGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxpay_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxpayGoods record);


    WxpayGoods selectDeliveryNumber(@Param("deliveryNumber") String deliveryNumber);

    void update(@Param("sysDeliveryNumber") String sysDeliveryNumber,@Param("dealtime") String dealtime,@Param("wxpayGdNumberId")int wxpayGdNumberId);

    WxpayGoods selectdeliveryNumberBysysDeliveryNumber(@Param("sysDeliveryNumber") String sysDeliveryNumber);

    void updateIsPayState(@Param("wxpayGdNumberId") int wxpayGdNumberId);

}